/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsMensaje;
import Clases.ClsEleccion;
import Controladores.CtlCandidato;
import Controladores.CtlEleccion;
import java.text.SimpleDateFormat;
import java.util.LinkedList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kaká
 */
public class FrmEleccion extends javax.swing.JFrame {

    JFrame frameMenu;

    CtlEleccion controlador;
    LinkedList<ClsEleccion> elecciones;

    CtlCandidato controladorCandidato;
    LinkedList<ClsCandidato> candidatos;

    /**
     * Creates new form FrmEleccion
     */
    public FrmEleccion(JFrame frameMenu) {
        initComponents();
        this.frameMenu = frameMenu;
        
        this.botonNuevo.setVisible(false);
        this.botonActualizar.setVisible(false);

        this.controlador = new CtlEleccion();
        this.controladorCandidato = new CtlCandidato();
        obtenerElecciones();
        obtenerCandidatos();
        campoId.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPestanias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboEleccion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FechaFin = new com.toedter.calendar.JDateChooser();
        comboEstado = new javax.swing.JComboBox<>();
        botonAgregar = new javax.swing.JButton();
        botonNuevo = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        campoId = new javax.swing.JTextField();
        FechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaElecciones = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCandidatos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        comboCandidato = new javax.swing.JComboBox<>();
        botonAsociar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        panelPestanias.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Descripción");

        jLabel3.setText("Tipo Elección");

        comboEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presidencial", "Legislativa", "Popular", " " }));

        jLabel4.setText("Fecha Inicio");

        jLabel5.setText("Fecha Fin");

        jLabel6.setText("Estado");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En Campaña", "En eleccion", "Finalizada" }));

        botonAgregar.setBackground(new java.awt.Color(255, 255, 204));
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        campoId.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Acciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(148, 148, 148)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboEstado, 0, 133, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(campoDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                            .addComponent(FechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botonActualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboEleccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonNuevo)
                            .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonAgregar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonActualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(12, 12, 12)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );

        panelPestanias.addTab("Formulario Elección", jPanel1);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablaElecciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Tipo", "Inicio", "fin", "Estado"
            }
        ));
        tablaElecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEleccionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaElecciones);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonEditar.setText("Editar");
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEliminar)
                .addGap(73, 73, 73)
                .addComponent(botonEditar)
                .addGap(110, 110, 110))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEliminar)
                    .addComponent(botonEditar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelPestanias.addTab("Listado Elección", jPanel2);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("GESTOR ELECCIONES");

        botonRegresar.setBackground(new java.awt.Color(204, 255, 204));
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        tablaCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Votos"
            }
        ));
        jScrollPane2.setViewportView(tablaCandidatos);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Candidatos por Elección");

        comboCandidato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        botonAsociar.setBackground(new java.awt.Color(255, 255, 204));
        botonAsociar.setText("Asociar");
        botonAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsociarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Seleccione Candidato");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAsociar)
                .addGap(34, 34, 34))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAsociar)
                .addContainerGap())
        );

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel9.setText("Nota: Para Asociar un candidato");

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel10.setText("Haga click en Listado Elección,");

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel11.setText("seleccione el registro, y haga");

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 1, 11)); // NOI18N
        jLabel12.setText("click en Asociar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(botonRegresar)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPestanias, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel12)))
                        .addGap(20, 20, 20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(botonRegresar))
                .addGap(18, 18, 18)
                .addComponent(panelPestanias, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.frameMenu.setVisible(true);
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        // TODO add your handling code here:
        String descripcion = campoDescripcion.getText();
        String eleccion = comboEleccion.getSelectedItem().toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //parsear al formato sql
        String fecha_inicio = sdf.format(this.FechaInicio.getDate());
        String fecha_fin = sdf.format(this.FechaFin.getDate());

        String estado = comboEstado.getSelectedItem().toString();

        String[] partesfecha = fecha_inicio.split("-", 2);

        String anio = partesfecha[0];

        String ideleccion = anio + eleccion.substring(0, 6);
        //JOptionPane.showMessageDialog(rootPane, date);

        ClsEleccion seleccion = new ClsEleccion(ideleccion, descripcion, eleccion, fecha_inicio, fecha_fin, estado);

        /**
         * preguntar a profesor De date = ic.jDate.getDate(); //ic es la
         * interfaz, jDate el JDatechooser long d = date.getTime(); //guardamos
         * en un long el tiempo java.sql.Date fecha = new java.sql.Date(d);//
         * parseamos al formato del sql at
         */
        ClsMensaje respuesta = this.controlador.agregareleccion(seleccion);
        // ahora verificamos que si se envia correctamente la info muestra un mensaje ok de lo contrario un error
        //luego se actualiza la tabla con candidadtos
        if (respuesta.getTipo().equals(ClsMensaje.OK)) {
            obtenerElecciones();
        }
        JOptionPane.showMessageDialog(rootPane, respuesta.getTexto());
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
        this.campoDescripcion.setText("");
        
        this.botonActualizar.setVisible(false);
        this.botonNuevo.setVisible(false);
        this.botonAgregar.setVisible(true);

    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsociarActionPerformed
        // TODO add your handling code here:
        int columna = 0;
        int fila = this.tablaElecciones.getSelectedRow();

        String ideleccion = this.tablaElecciones.getModel().getValueAt(fila, columna).toString();

        //guardo en un array lo que trae de la base de datos candidatos y luego selecciono solo el id con split
        String[] partecandidato = this.comboCandidato.getSelectedItem().toString().split("-");

        String idcandidato = partecandidato[1];

        ClsMensaje mensaje = this.controlador.asociarcandidato(ideleccion, idcandidato);

        if (mensaje.getTipo().equals(ClsMensaje.OK)) {
            //obtenerElecciones();
            this.obtenerCandidatoseleccion(ideleccion);
        }
        
         JOptionPane.showMessageDialog(rootPane, mensaje.getTexto());

    }//GEN-LAST:event_botonAsociarActionPerformed

    private void tablaEleccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEleccionesMouseClicked
        // TODO add your handling code here:
        int columna = 0;
        int fila = this.tablaElecciones.getSelectedRow();

        String ideleccion = this.tablaElecciones.getModel().getValueAt(fila, columna).toString();
        this.obtenerCandidatoseleccion(ideleccion);

    }//GEN-LAST:event_tablaEleccionesMouseClicked

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // TODO add your handling code here:
         //aca obtengo en este caso lo que hay almacenado en memoria la primera columna correspondiente al id
        int columna=0;
        int fila = this.tablaElecciones.getSelectedRow();
        
        String ideleccion = this.tablaElecciones.getModel().getValueAt(fila, columna).toString();
        
        ClsEleccion eleccion=this.BuscarEleccion(ideleccion);
        //ahora lo que retorna en la variable candidato se envia a todos los campos del formulario
        if(eleccion!=null){
            //deshabilitar el campo documento toda vez que por recomendacion no se deberia actualizar
            this.botonNuevo.setVisible(true);
            this.botonActualizar.setVisible(true);
            
            //ocultar el boton agregar
            this.botonAgregar.setVisible(false);
            
        
            this.campoDescripcion.setText(eleccion.getDescripcion());
            this.campoId.setText(eleccion.getId());
            
        }
        this.panelPestanias.setSelectedIndex(0);
        
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        String descripcion = campoDescripcion.getText();
        String eleccion = comboEleccion.getSelectedItem().toString();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        //parsear al formato sql
        String fecha_inicio = sdf.format(this.FechaInicio.getDate());
        String fecha_fin = sdf.format(this.FechaFin.getDate());

        String estado = comboEstado.getSelectedItem().toString();
        String ideleccion=campoId.getText();
                
        //JOptionPane.showMessageDialog(rootPane, date);

        ClsEleccion seleccion = new ClsEleccion(ideleccion, descripcion, eleccion, fecha_inicio, fecha_fin, estado);

        /**
         * preguntar a profesor De date = ic.jDate.getDate(); //ic es la
         * interfaz, jDate el JDatechooser long d = date.getTime(); //guardamos
         * en un long el tiempo java.sql.Date fecha = new java.sql.Date(d);//
         * parseamos al formato del sql at
         */
        ClsMensaje respuesta = this.controlador.actualizareleccion(seleccion);
        // ahora verificamos que si se envia correctamente la info muestra un mensaje ok de lo contrario un error
        //luego se actualiza la tabla con candidadtos
        if (respuesta.getTipo().equals(ClsMensaje.OK)) {
            obtenerElecciones();
        }
        JOptionPane.showMessageDialog(rootPane, respuesta.getTexto());
        
        
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
         int columna=0;
        int fila = this.tablaElecciones.getSelectedRow();
        
        String ideleccion = this.tablaElecciones.getModel().getValueAt(fila, columna).toString();
        
        //una vez recibida la informacion la enviamos al controlador con la sigueinte linea
        ClsMensaje respuesta=this.controlador.eliminareleccion(ideleccion);
        
        
        // ahora verificamos que si se envia correctamente la info muestra un mensaje ok de lo contrario un error
        //luego se actualiza la tabla con candidadtos
        if (respuesta.getTipo().equals(ClsMensaje.OK)) {
        obtenerElecciones();
        }
        JOptionPane.showMessageDialog(rootPane, respuesta.getTexto());
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    //metodo para traer datos y cargarlos al combo de candidatos
    public void obtenerCandidatos() {
        this.candidatos = this.controladorCandidato.obtenerCandidatos();
        this.ActualizarComboCandidato(this.candidatos);
    }

    //metodo para actualizacion al combo candidato
    private void ActualizarComboCandidato(LinkedList<ClsCandidato> lista) {

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) this.comboCandidato.getModel();

        modelo.removeAllElements();

        //realiza un recorrrido a los datos a partir del ciclo for 
        for (ClsCandidato c : lista) {

            String candidato = c.getNombre() + '-' + c.getNumeroDocumento();
            modelo.addElement(candidato);

        }
    }

    //metodo para actualizar la tabla elecciones
    public void obtenerElecciones() {
        this.elecciones = this.controlador.obtenerElecciones();
        this.ActualizarTabla(elecciones);
    }

    //metodo para actualizar tabla de candidatos con asociacion
    public void obtenerCandidatoseleccion(String ideleccion) {
        LinkedList<ClsCandidato> listacandidatos = this.controlador.obtenerCandidatoseleccion(ideleccion);
        this.ActualizarTablacandidatos(listacandidatos);
    }

    //metodo para actualizar la tabla donde estan las elecciones
    private void ActualizarTabla(LinkedList<ClsEleccion> lista) {
        DefaultTableModel modelo = (DefaultTableModel) tablaElecciones.getModel();
        modelo.setRowCount(0);

        //realiza un recorrrido a los datos a partir del ciclo for 
        for (ClsEleccion c : lista) {
            Object[] fila = {c.getId(), c.getTipo(), c.getFecha_inicio(), c.getFecha_fin(), c.getEstado()};
            modelo.addRow(fila);
        }
    }

    //metodo para actualizar la tabla donde estan las asociaciones de los candidatos
    private void ActualizarTablacandidatos(LinkedList<ClsCandidato> lista) {
        DefaultTableModel modelo = (DefaultTableModel) this.tablaCandidatos.getModel();
        modelo.setRowCount(0);

        //realiza un recorrrido a los datos a partir del ciclo for 
        for (ClsCandidato c : lista) {
            Object[] fila = {c.getNumeroDocumento(), c.getNombre(), ""};
            modelo.addRow(fila);
        }
    }
    
    //metodo para buscar un tipo de eleccion y editar
    public ClsEleccion BuscarEleccion(String ideleccion){
        for(ClsEleccion eleccion:this.elecciones){
            if(eleccion.getId().equals(ideleccion)){
            return eleccion;
            }
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEleccion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEleccion(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser FechaFin;
    private com.toedter.calendar.JDateChooser FechaInicio;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAsociar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField campoDescripcion;
    private javax.swing.JTextField campoId;
    private javax.swing.JComboBox<String> comboCandidato;
    private javax.swing.JComboBox<String> comboEleccion;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane panelPestanias;
    private javax.swing.JTable tablaCandidatos;
    private javax.swing.JTable tablaElecciones;
    // End of variables declaration//GEN-END:variables
}
